### ISSUE TITLE
Review Pat

### ISSUE THREAD

**Issue by pat-s** [cynkra/cynkrablog#36]
@maelle Thanks for your work so far! I've noted down some of my observations while looking at the new site. They are mainly cosmetic details, and I am not responsible for these (@christophsax is) but maybe they are still helpful...

## ToDos

- [ ] Align navbar height in dark and light theme
- [ ] Align container width of post preview's between dark and light theme
- [ ] Align button colors (e.g. page buttons) of both dark and light theme with cynkraweb colors
- [x] Add a workflow for previews in PRs (copy from cynkraweb)
- [ ] Dark theme: navbar should also be dark
- [ ] Align link color in posts with blue used in cynkraweb
- [x] Don't linebreak "Except where otherwise noted, content on this blog is licensed under the [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) license."
- [x] Align capitalization in navbar dropdowns with cynkraweb.
- [ ] Can we link the author names in posts to https://cynkra.com/about?

## Further questions
- Do we want the "reader mode toggle" switch?
- how to stay in sync with changes in cynkraweb? Can we use the cynkraweb navbar in cynkrablog dynamically?

**Comment by maelle** [comment]
> how to stay in sync with changes in cynkraweb? Can we use the cynkraweb navbar in cynkrablog dynamically?

The last time the cynkraweb navbar was updated, I noticed thanks to lychee! I'd say it's enough automation for now?

**Comment by maelle** [comment]
The dark theme is really a work in progress, maybe it should be removed completely as long as #18 isn't finished.

**Comment by pat-s** [comment]
> The last time the cynkraweb navbar was updated, I noticed thanks to lychee! I'd say it's enough automation for now?

Hmm, but nobody will notice/know that changes are needed in cynkrablog when changes are applied in cynkraweb. And then the blog is out of sync for quite some time, I guess. This is a detail but looks quite unprofessional when it happens.

I didn't look into the code but why not implement a scrape action which automatically syncs this HTML code part from cynkraweb? (in case it's pure HTML)

**Comment by pat-s** [comment]
> The dark theme is really a work in progress, maybe it should be removed completely as long as https://github.com/cynkra/cynkrablog/pull/18 isn't finished.

IMO we should rather invest time in getting it working as it's quite disturbing when everything is dark but the blog becomes light, especially during winter time when the "dark theme time" is quite long.

**Comment by maelle** [comment]
>

I don't think there's anything built-in Quarto yet. https://github.com/quarto-dev/quarto-cli/issues/4669

**Comment by maelle** [comment]
>  Align link color in posts with blue used in cynkraweb

But that blue `#5582FD` doesn't provide enough contrast according to this [contrast checker](https://webaim.org/resources/contrastchecker/)

**Comment by maelle** [comment]
@pat-s how is the navbar configured in cynkraweb?

**Comment by maelle** [comment]
>  Align button colors (e.g. page buttons) of both dark and light theme with cynkraweb colors

I don't understand what those buttons are.

**Comment by maelle** [comment]
one incomplete idea for buttons if they are the things at the right of the navbar.

```
// button

a i.bi, button {
  color: rgb(24, 79, 169) !important;
}
```

**Comment by christophsax** [comment]
@maelle, to me, what we have on https://blog.cynkra.com certainly looks good enough. I would prefer to make this the actual blog linked from the website asap. We can iterate on the other points (such as dark mode) as we move along (and write blogs again!).

**Comment by maelle** [comment]
@pat-s how is the navbar configured in cynkraweb?
